# Generated by Django 4.2.9 on 2024-03-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_size_without_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreImageOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='extra_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_imag', to='product.moreimageofproduct'),
        ),
    ]
