# Generated by Django 4.2.9 on 2024-03-29 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_moreimageofproduct_product_extra_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreimageofproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_extra_image', to='product.product'),
        ),
    ]
