# Generated by Django 4.2.9 on 2024-03-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_extra_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moreimageofproduct',
            name='name',
        ),
    ]
