# Generated by Django 4.2.9 on 2024-03-30 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_moreimageofproduct_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size_without_variant',
            new_name='size_diameter',
        ),
        migrations.AddField(
            model_name='product',
            name='size_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_length',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_surface_density',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_thickness',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_width',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_designer', models.TextField(blank=True, max_length=255, null=True)),
                ('goodToKnow', models.TextField(blank=True, max_length=255, null=True)),
                ('material', models.TextField(blank=True, max_length=255, null=True)),
                ('care', models.TextField(blank=True, max_length=255, null=True)),
                ('safety_compliance', models.TextField(blank=True, max_length=255, null=True)),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_details', to='product.product')),
            ],
        ),
    ]
