# Generated by Django 4.2.9 on 2024-03-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_size_without_variant_product_size_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
