# Generated by Django 4.2.9 on 2024-03-30 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_size_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_length', models.CharField(blank=True, max_length=255, null=True)),
                ('pack_width', models.CharField(blank=True, max_length=255, null=True)),
                ('pack_height', models.CharField(blank=True, max_length=255, null=True)),
                ('pack_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('pack_area', models.CharField(blank=True, max_length=255, null=True)),
                ('pack_diameter', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_package', to='product.product')),
            ],
        ),
    ]
