# Generated by Django 4.2.9 on 2024-03-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='care',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='description_designer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='goodToKnow',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='safety_compliance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
