# Generated by Django 4.2.9 on 2024-03-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productdetails_care_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packaging',
            old_name='details',
            new_name='package',
        ),
    ]
