# Generated by Django 4.2.9 on 2024-03-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rename_details_packaging_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='details',
            new_name='product',
        ),
    ]
