# Generated by Django 4.2.9 on 2024-03-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_details_productdetails_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moreimageofproduct',
            old_name='product',
            new_name='x',
        ),
    ]
