# Generated by Django 4.2.9 on 2024-03-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_color_product_discount_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('color', 'Color')], default='none', max_length=6),
        ),
    ]
