# Generated by Django 4.2.9 on 2024-03-31 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_variant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimension_vars', to='product.dimension'),
        ),
    ]
