# Generated by Django 4.2.9 on 2024-03-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_variant_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('color', 'Color'), ('size', 'Size'), ('size_color', 'Size_Color_Var')], default='none', max_length=20),
        ),
    ]
