# Generated by Django 4.2.9 on 2024-04-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_tagrelated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagrelated',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags_related_product', to='product.tagrelated'),
        ),
    ]
