# Generated by Django 4.2.9 on 2024-04-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_remove_tagrelated_tag_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_area',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_diameter',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_height',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_length',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_surface_density',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_thickness',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_weight',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_width',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
