# Generated by Django 4.2.9 on 2024-04-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_product_size_area_alter_product_size_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scroll_show',
            field=models.BooleanField(default=True),
        ),
    ]
