# Generated by Django 4.2.9 on 2024-04-03 02:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0036_comment_is_reply_comment_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.ManyToManyField(blank=True, related_name='liked_comments', to='product.comment')),
                ('product', models.ManyToManyField(blank=True, related_name='liked_products', to='product.product')),
                ('user_liker_product', models.ManyToManyField(blank=True, related_name='user_like_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
