# Generated by Django 4.2.9 on 2024-04-03 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0039_remove_like_comment_remove_like_product_like_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user_liker_product',
        ),
        migrations.AddField(
            model_name='like',
            name='user_liker_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_like_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
