# Generated by Django 4.2.9 on 2024-04-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_remove_like_user_liker_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_liked', to='product.like'),
        ),
    ]
