# Generated by Django 4.2.9 on 2024-04-03 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0042_remove_like_likers_comment_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likers',
        ),
        migrations.AddField(
            model_name='product',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='pr_liked_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
