# Generated by Django 4.2.9 on 2024-04-03 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0045_comment_dislikers'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likers_reply',
            field=models.ManyToManyField(blank=True, related_name='comment_reply_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
