# Generated by Django 4.2.9 on 2024-04-21 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_product_total_sale_variant_total_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen', to='product.product')),
            ],
        ),
    ]
