# Generated by Django 4.2.9 on 2024-04-23 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0050_productseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likers_reply',
            field=models.ManyToManyField(blank=True, default='fa-regular', related_name='comment_reply_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
