# Generated by Django 4.2.9 on 2024-04-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_street',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_birthday',
            field=models.DateField(null=True),
        ),
    ]
