# Generated by Django 4.2.9 on 2024-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_city_user_address_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_street',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
