# Generated by Django 4.2.9 on 2024-04-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='to_date',
            field=models.DateTimeField(),
        ),
    ]
